### ISSUE TITLE
add a way to change the controls

### ISSUE THREAD

**Issue by pixelr0** [MitchelPaulin/CTris#1]
add a way to change the controls. even a config file
i would rather use the arrow keys. the most annoying control is E right next to W :))
i've unintentionally exited the game countless times! also maybe an exit confirmation dialog would be nice

T H A N K S 

\O/

**Comment by MitchelPaulin** [comment]
I think adding a config file may be a bit overkill. But I do agree the arrow keys should be enabled and the exit button should not be so close to WASD. What I'll do is add arrow key support so both WASD and arrows will work and change the exit key from E to ESC to avoid accidental presses.

**Comment by MitchelPaulin** [comment]
@pixelr0 You should be able to install version 1.1 now :).

**Comment by pixelr0** [comment]
Thanks! works great now! :D
